AppRegistry.register('gameemulator', {
  name: 'Game Emulator',
  iconBg: 'linear-gradient(135deg, #ef4444, #7c3aed)',
  iconText: '🎮',
  render(container) {
    const API_BASE = window.VeyraRuntime?.apiBase || 'https://veyraserver-xscy.onrender.com';
    const libraryKey = 'veyra-games-library';
    const downloadsKey = 'veyra-games-downloads';
    let library = OSStorage.get(libraryKey, []);
    let downloads = OSStorage.get(downloadsKey, []);
    let activeGame = null;
    let activeObjectUrl = '';
    const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
    const id = () => `game_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    const save = () => { OSStorage.set(libraryKey, library); OSStorage.set(downloadsKey, downloads); };
    const demoGame = () => `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"><style>html,body{margin:0;height:100%;overflow:hidden;background:#101425;color:#fff;font:16px system-ui}canvas{display:block;width:100%;height:100%;touch-action:none}#hint{position:fixed;top:12px;left:0;right:0;text-align:center;opacity:.75}#pad{position:fixed;bottom:18px;left:18px;right:18px;display:flex;justify-content:space-between;pointer-events:none}button{pointer-events:auto;border:1px solid #ffffff40;border-radius:16px;background:#ffffff18;color:#fff;font-size:24px;width:64px;height:54px}</style></head><body><canvas id="c"></canvas><div id="hint">VEYRA RUNNER · tap or press Space to jump</div><div id="pad"><button id="jump">↑</button><button id="restart">↻</button></div><script>const c=document.getElementById('c'),x=c.getContext('2d');let d=devicePixelRatio||1,w=0,h=0,player,blocks,score,over,last=0;function size(){w=innerWidth;h=innerHeight;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0)}function reset(){player={x:70,y:h-100,vy:0};blocks=[];score=0;over=false}function jump(){if(over)return reset();if(player.y>=h-105)player.vy=-15}function frame(t){let dt=Math.min(32,t-last)/16;last=t;x.clearRect(0,0,w,h);x.fillStyle='#151d39';x.fillRect(0,0,w,h);x.fillStyle='#27355d';x.fillRect(0,h-55,w,55);if(!over){player.vy+=.75*dt;player.y+=player.vy*dt;if(player.y>h-100)player.y=h-100;if(Math.random()<.025*dt)blocks.push({x:w+20,y:h-85,w:24+Math.random()*30,h:30+Math.random()*35});blocks.forEach(b=>b.x-=6*dt);blocks=blocks.filter(b=>b.x>-60);for(const b of blocks)if(player.x+28>b.x&&player.x<b.x+b.w&&player.y+28>b.y){over=true}score+=dt*.1}x.fillStyle='#8fb0f0';x.fillRect(player.x,player.y,28,28);x.fillStyle='#f87171';blocks.forEach(b=>x.fillRect(b.x,b.y,b.w,b.h));x.fillStyle='#fff';x.font='700 18px system-ui';x.fillText('Score '+Math.floor(score),16,42);if(over){x.textAlign='center';x.font='700 28px system-ui';x.fillText('Game over',w/2,h/2);x.font='16px system-ui';x.fillText('Tap ↻ to restart',w/2,h/2+30);x.textAlign='left'}requestAnimationFrame(frame)}addEventListener('resize',()=>{size();if(!player)reset()});addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp')jump()});document.getElementById('jump').onclick=jump;document.getElementById('restart').onclick=reset;size();reset();requestAnimationFrame(frame);</script></body></html>`;
    function gameCard(game) {
      return `<article class="ve-game-card"><div class="ve-game-art">${game.kind === 'demo' ? '🏃' : '🕹️'}</div><div class="ve-game-info"><b>${esc(game.name)}</b><small>${esc(game.format || 'HTML5')} · ${new Date(game.addedAt).toLocaleDateString()}</small></div><button class="btn primary sm" data-play="${esc(game.id)}">Play</button><button class="btn ghost sm" data-remove="${esc(game.id)}">×</button></article>`;
    }
    function render() {
      container.innerHTML = `<div class="ve-emulator"><header class="ve-emulator-head"><div><span class="ve-eyebrow">VEYRA GAME RUNTIME</span><h2>Game Emulator</h2><p>Load your own HTML5 games, download games from a URL, or play the built-in demo.</p></div><span class="ve-runtime-pill">● Ready</span></header><nav class="ve-emulator-tabs"><button class="ve-tab active" data-tab="library">Library</button><button class="ve-tab" data-tab="import">Import game</button><button class="ve-tab" data-tab="downloads">Downloads <span>${downloads.length}</span></button></nav><main class="ve-emulator-main"><section class="ve-panel" data-panel="library"><div class="ve-section-head"><div><b>Your games</b><small>Games run in a sandboxed iframe.</small></div><button class="btn primary sm" data-action="demo">Play demo</button></div><div class="ve-game-grid">${library.map(gameCard).join('') || '<div class="ve-empty">Your library is empty. Import an HTML game or try Veyra Runner.</div>'}</div><div class="ve-legal-note">Only load games you own or have permission to use. This runtime does not include copyrighted ROMs or console firmware.</div></section><section class="ve-panel hidden" data-panel="import"><div class="ve-section-head"><div><b>Import a game</b><small>HTML and JavaScript games work best on mobile.</small></div></div><label class="ve-drop"><input id="veGameFile" type="file" accept=".html,.htm,.js,.json,text/html,application/javascript"><span>Choose a local game file</span><small>HTML, HTM, JS or JSON game bundles</small></label><div class="ve-divider">or download from a URL</div><form id="veUrlForm"><input id="veGameUrl" class="input" type="url" placeholder="https://example.com/my-game.html" required><button class="btn primary" type="submit">Download game</button></form><p class="ve-form-note">Downloads use the configured Veyra API resource route when direct browser access is blocked.</p></section><section class="ve-panel hidden" data-panel="downloads"><div class="ve-section-head"><div><b>Game downloads</b><small>Recent files fetched for the emulator.</small></div></div><div class="ve-download-list">${downloads.map(item => `<div class="ve-download-row"><span>${item.status === 'complete' ? '✓' : '…'}</span><div><b>${esc(item.name)}</b><small>${esc(item.url)}</small></div><em>${esc(item.status)}</em></div>`).join('') || '<div class="ve-empty">No game downloads yet.</div>'}</div></section></main><div class="ve-player hidden" id="vePlayer"><div class="ve-player-head"><b id="vePlayerTitle">Game</b><button class="btn ghost sm" id="veClosePlayer">Close</button></div><iframe id="veGameFrame" sandbox="allow-scripts allow-forms allow-pointer-lock" title="Veyra game runtime"></iframe></div></div>`;
      bind();
    }
    function bind() {
      container.querySelectorAll('[data-tab]').forEach(button => button.onclick = () => { container.querySelectorAll('[data-tab]').forEach(item => item.classList.toggle('active', item === button)); container.querySelectorAll('[data-panel]').forEach(panel => panel.classList.toggle('hidden', panel.dataset.panel !== button.dataset.tab)); });
      container.querySelector('[data-action="demo"]').onclick = () => addGame({ id: id(), name: 'Veyra Runner', kind: 'demo', format: 'HTML5', source: demoGame(), addedAt: Date.now() }, true);
      container.querySelectorAll('[data-play]').forEach(button => button.onclick = () => playGame(button.dataset.play));
      container.querySelectorAll('[data-remove]').forEach(button => button.onclick = () => { library = library.filter(game => game.id !== button.dataset.remove); save(); render(); });
      container.querySelector('#veClosePlayer').onclick = () => { container.querySelector('#vePlayer').classList.add('hidden'); container.querySelector('#veGameFrame').srcdoc = ''; };
      container.querySelector('#veGameFile').onchange = event => { const file = event.target.files?.[0]; if (file) importFile(file); };
      container.querySelector('#veUrlForm').onsubmit = event => { event.preventDefault(); const url = container.querySelector('#veGameUrl').value.trim(); if (url) downloadGame(url); };
    }
    function addGame(game, launch) { library = [game, ...library.filter(item => item.id !== game.id)]; save(); render(); if (launch) playGame(game.id); }
    function playGame(gameId) { const game = library.find(item => item.id === gameId); if (!game) return; activeGame = game; const player = container.querySelector('#vePlayer'); container.querySelector('#vePlayerTitle').textContent = game.name; const frame = container.querySelector('#veGameFrame'); frame.srcdoc = game.source; player.classList.remove('hidden'); }
    function importFile(file) { const reader = new FileReader(); reader.onload = () => { const source = String(reader.result || ''); if (!source) return; const game = { id: id(), name: file.name.replace(/\.[^.]+$/, ''), kind: 'local', format: file.name.split('.').pop().toUpperCase(), source: file.name.toLowerCase().endsWith('.js') ? `<!doctype html><html><body><script>${source.replace(/<\/script/gi, '<\\/script')}<\/script></body></html>` : source, addedAt: Date.now() }; addGame(game, false); Toast.show('Game Emulator', `${file.name} added to your library`, '🎮'); }; reader.readAsText(file); }
    async function downloadGame(url) { const name = url.split('/').pop().split('?')[0] || 'downloaded-game.html'; downloads = [{ name, url, status: 'downloading', time: Date.now() }, ...downloads]; save(); render(); try { let response; try { response = await fetch(url); } catch { response = await fetch(`${API_BASE}/api/resource?url=${encodeURIComponent(url)}`); } if (!response.ok) throw new Error(`Download failed with HTTP ${response.status}`); const source = await response.text(); downloads[0].status = 'complete'; const game = { id: id(), name: name.replace(/\.[^.]+$/, ''), kind: 'download', format: 'HTML5', source, addedAt: Date.now() }; addGame(game, false); Toast.show('Game Emulator', 'Game downloaded and added', '🎮'); } catch (error) { downloads[0].status = 'failed'; save(); render(); Toast.show('Game Emulator', error.message, '⚠️'); } }
    render();
  }
});
